# **Introduction to TensorFlow**

## **Creating tensors**

#### **Using tf.constant()**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
print(tf.__version__)

2024-06-30 18:30:58.384304: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


2.4.1


In [2]:
scalar = tf.constant(7)

2024-06-30 18:30:59.783659: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-06-30 18:30:59.785048: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-06-30 18:30:59.976387: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-30 18:30:59.976496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2024-06-30 18:30:59.976526: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2024-06-30 18:30:59.986429: I tensorflow/stream_executor/platf

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([42, 42])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[42, 24],
                      [42, 24]])

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
matrix_2 = tf.constant([[42, 24],
                        [42, 24],
                        [12, 21]], dtype = tf.float16)

In [12]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.],
       [12., 21.]], dtype=float16)>

In [13]:
matrix_2.ndim

2

In [14]:
tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

In [15]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [16]:
tensor.ndim

3

#### **Using tf.variable()**

In [17]:
changeable_tensor = tf.Variable([42, 24])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([42, 24], dtype=int32)>

In [18]:
unchangeable_tensor = tf.constant([42, 24])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 24], dtype=int32)>

In [19]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [20]:
changeable_tensor[0] = 24

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
changeable_tensor[0].assign(24)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [22]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [23]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [24]:
unchangeable_tensor[0] = 24    

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [25]:
unchangeable_tensor[0].assign(24)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#### **Creating random tensors**

In [27]:
random_1 = tf.random.Generator.from_seed(42)

In [28]:
random_1

In [29]:
random_1 = random_1.normal(shape = (3, 2))

In [30]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [31]:
random_2 = tf.random.Generator.from_seed(42)

In [32]:
random_2

In [33]:
random_2 = random_2.normal(shape = (3, 2))

In [34]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [35]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [36]:
tf.random.set_seed(42)
tf.random.shuffle(random_1, seed = 24)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

#### **Create tensors using numpy arrays and pandas dataframes**

In [37]:
tf.ones(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [38]:
tf.zeros(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [39]:
numpy_A = np.arange(1, 25, dtype = np.int32)

In [40]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [41]:
numpy_A = numpy_A.reshape((4, 6))

In [42]:
n_A = tf.constant(numpy_A)

In [43]:
n_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [44]:
n_B = tf.constant(numpy_A, shape = (2, 3, 4))

In [45]:
n_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [46]:
pandas_A = pd.DataFrame(numpy_A)

In [47]:
pandas_A

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24

In [48]:
p_A = tf.constant(pandas_A)

In [49]:
p_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [50]:
p_B = tf.constant(pandas_A, shape = (2, 3, 4))

In [51]:
p_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [52]:
p_B.ndim

3

## **Getting information from tensors**

In [53]:
print(f'Shape: {p_A.shape}, Rank: {p_A.ndim}, Size: {tf.size(p_A)}')

Shape: (4, 6), Rank: 2, Size: 24


In [54]:
import re
def get_tensor_attributes(tensor):
    shape = tensor.shape
    rank = tensor.ndim
    size = tf.size(tensor)
    d_type = f'{tensor.dtype}'.split(':')[1]
    d_type = re.sub(r'[\W]', '', d_type)
    
    return shape, rank, size, d_type

In [55]:
shape, rank, size, d_type = get_tensor_attributes(p_A)
print(f'Shape: {shape}, Rank: {rank}, Size: {size}, Datatype: {d_type}')

Shape: (4, 6), Rank: 2, Size: 24, Datatype: int32


## **Indexing tensors**

In [56]:
rank_4_tensor = tf.constant(np.arange(1, 121), shape = (2, 3, 4, 5))

In [57]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [58]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]])>

In [59]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [60]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int64, numpy=
array([[[[ 1],
         [ 6],
         [11],
         [16]]]])>

In [61]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=int64, numpy=
array([[[[ 1]],

        [[21]],

        [[41]]]])>

In [62]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int64, numpy=
array([[[[ 1]]],


       [[[61]]]])>

In [63]:
rank_2_tensor = tf.reshape(rank_4_tensor, shape = (8, 15))

In [64]:
rank_2_tensor

<tf.Tensor: shape=(8, 15), dtype=int64, numpy=
array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
         59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120]])>

In [65]:
rank_2_tensor[:, :5]

<tf.Tensor: shape=(8, 5), dtype=int64, numpy=
array([[  1,   2,   3,   4,   5],
       [ 16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35],
       [ 46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65],
       [ 76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95],
       [106, 107, 108, 109, 110]])>

In [66]:
rank_2_tensor_1 = tf.constant([[42, 24], [21, 12]])

In [67]:
rank_2_tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [68]:
rank_2_tensor_1[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([24, 12], dtype=int32)>

In [69]:
rank_3_tensor = rank_2_tensor_1[..., tf.newaxis]

In [70]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[42],
        [24]],

       [[21],
        [12]]], dtype=int32)>

In [71]:
tf.expand_dims(rank_2_tensor_1, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[42],
        [24]],

       [[21],
        [12]]], dtype=int32)>

## **Manupilating tensors**

In [72]:
some_tensor = tf.constant([[42, 24], [21, 12]])

In [73]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [74]:
some_tensor = some_tensor + 42

In [75]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[84, 66],
       [63, 54]], dtype=int32)>

In [76]:
some_tensor = some_tensor - 42

In [77]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [78]:
some_tensor = some_tensor * 4

In [79]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[168,  96],
       [ 84,  48]], dtype=int32)>

In [80]:
some_tensor = some_tensor // 4

In [81]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [82]:
some_tensor = some_tensor / 2

In [83]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[21. , 12. ],
       [10.5,  6. ]])>

In [84]:
import numpy as np

In [85]:
some_tensor = np.sqrt(some_tensor)

In [86]:
some_tensor

array([[4.58257569, 3.46410162],
       [3.24037035, 2.44948974]])

In [87]:
some_tensor = pow(some_tensor, 2)

In [88]:
some_tensor

array([[21. , 12. ],
       [10.5,  6. ]])

In [89]:
some_tensor = some_tensor * 2 

In [90]:
some_tensor

array([[42., 24.],
       [21., 12.]])

In [91]:
some_tensor = tf.cast(some_tensor, 'int32')

In [92]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 23],
       [21, 11]], dtype=int32)>

In [93]:
tf.math.add(some_tensor, 8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 31],
       [29, 19]], dtype=int32)>

In [94]:
tf.math.subtract(some_tensor, 13)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 10],
       [ 8, -2]], dtype=int32)>

In [95]:
tf.math.multiply(some_tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[168,  92],
       [ 84,  44]], dtype=int32)>

In [96]:
tf.math.divide(some_tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[14.        ,  7.66666667],
       [ 7.        ,  3.66666667]])>

## **Matrix multiplication**

In [97]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 23],
       [21, 11]], dtype=int32)>

In [98]:
some_tensor_t = tf.transpose(some_tensor)

In [99]:
some_tensor_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 21],
       [23, 11]], dtype=int32)>

In [100]:
tf.math.multiply(some_tensor, some_tensor_t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1764,  483],
       [ 483,  121]], dtype=int32)>

In [101]:
tf.linalg.matmul(some_tensor, some_tensor_t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2293, 1135],
       [1135,  562]], dtype=int32)>

In [102]:
matrix1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

In [103]:
matrix2 = tf.constant([
    [7, 8],
    [10, 11],
    [13, 14]
])

In [104]:
tf.linalg.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 66,  72],
       [156, 171]], dtype=int32)>

In [105]:
matrix3 = tf.constant(np.random.randint(1, 100, 12).reshape(3, 4))

In [106]:
matrix3

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[34, 52, 34, 83],
       [12, 29, 43, 71],
       [40, 18,  1,  8]])>

In [107]:
matrix4 = tf.constant(np.random.randint(1, 100, 8).reshape(4, 2))

In [108]:
matrix4

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[82, 91],
       [60, 31],
       [61, 17],
       [83, 90]])>

In [109]:
tf.tensordot(matrix3, matrix4, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[14871, 12754],
       [11240,  9112],
       [ 5085,  4935]])>

In [110]:
tf.matmul(matrix3, matrix4)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[14871, 12754],
       [11240,  9112],
       [ 5085,  4935]])>

## **Changing tensors datatype**

In [125]:
matrix3 = tf.cast(matrix3, dtype = tf.int32)

In [126]:
matrix4 = tf.cast(matrix4, dtype = tf.int32)

In [127]:
tf.matmul(matrix3, matrix4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14871, 12754],
       [11240,  9112],
       [ 5085,  4935]], dtype=int32)>