# **Introduction to TensorFlow**

## **Creating tensors**

#### **Using tf.constant()**

In [1]:
import tensorflow as tf
print(tf.__version__)

2024-05-04 11:26:39.812964: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


2.4.1


In [2]:
scalar = tf.constant(7)

2024-05-04 11:26:41.703333: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-05-04 11:26:41.704053: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-05-04 11:26:41.993710: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-04 11:26:41.993758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2024-05-04 11:26:41.993775: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2024-05-04 11:26:42.023267: I tensorflow/stream_executor/platf

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([42, 42])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[42, 24],
                      [42, 24]])

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
matrix_2 = tf.constant([[42, 24],
                        [42, 24],
                        [12, 21]], dtype = tf.float16)

In [12]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.],
       [12., 21.]], dtype=float16)>

In [13]:
matrix_2.ndim

2

In [14]:
tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

In [15]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [16]:
tensor.ndim

3

#### **Using tf.variable()**

In [18]:
changeable_tensor = tf.Variable([42, 24])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([42, 24], dtype=int32)>

In [19]:
unchangeable_tensor = tf.constant([42, 24])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 24], dtype=int32)>

In [20]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [23]:
changeable_tensor[0] = 24

TypeError: 'ResourceVariable' object does not support item assignment

In [24]:
changeable_tensor[0].assign(24)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [26]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [29]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [27]:
unchangeable_tensor[0] = 24    

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [28]:
unchangeable_tensor[0].assign(24)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'