# **Introduction to TensorFlow**

## **Creating tensors**

#### **Using tf.constant()**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
print(tf.__version__)

2024-06-28 21:47:25.691233: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


2.4.1


In [2]:
scalar = tf.constant(7)

2024-06-28 21:47:27.081362: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-06-28 21:47:27.082460: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-06-28 21:47:27.263938: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-28 21:47:27.263991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2024-06-28 21:47:27.264019: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2024-06-28 21:47:27.268014: I tensorflow/stream_executor/platf

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([42, 42])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[42, 24],
                      [42, 24]])

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
matrix_2 = tf.constant([[42, 24],
                        [42, 24],
                        [12, 21]], dtype = tf.float16)

In [12]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.],
       [12., 21.]], dtype=float16)>

In [13]:
matrix_2.ndim

2

In [14]:
tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

In [15]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [16]:
tensor.ndim

3

#### **Using tf.variable()**

In [17]:
changeable_tensor = tf.Variable([42, 24])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([42, 24], dtype=int32)>

In [18]:
unchangeable_tensor = tf.constant([42, 24])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 24], dtype=int32)>

In [19]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [20]:
changeable_tensor[0] = 24

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
changeable_tensor[0].assign(24)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [22]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [23]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [24]:
unchangeable_tensor[0] = 24    

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [25]:
unchangeable_tensor[0].assign(24)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#### **Creating random tensors**

In [27]:
random_1 = tf.random.Generator.from_seed(42)

In [28]:
random_1

In [29]:
random_1 = random_1.normal(shape = (3, 2))

In [30]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [31]:
random_2 = tf.random.Generator.from_seed(42)

In [32]:
random_2

In [33]:
random_2 = random_2.normal(shape = (3, 2))

In [34]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [35]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [36]:
tf.random.set_seed(42)
tf.random.shuffle(random_1, seed = 24)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

#### **Create tensors using numpy arrays and pandas dataframes**

In [37]:
tf.ones(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [38]:
tf.zeros(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [39]:
numpy_A = np.arange(1, 25, dtype = np.int32)

In [40]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [41]:
numpy_A = numpy_A.reshape((4, 6))

In [42]:
n_A = tf.constant(numpy_A)

In [43]:
n_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [44]:
n_B = tf.constant(numpy_A, shape = (2, 3, 4))

In [45]:
n_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [46]:
pandas_A = pd.DataFrame(numpy_A)

In [47]:
pandas_A

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24

In [48]:
p_A = tf.constant(pandas_A)

In [49]:
p_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [50]:
p_B = tf.constant(pandas_A, shape = (2, 3, 4))

In [51]:
p_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [52]:
p_B.ndim

3

#### **Getting information from tensors**

In [61]:
print(f'Shape: {p_A.shape}, Rank: {p_A.ndim}, Size: {tf.size(p_A)}')

Shape: (4, 6), Rank: 2, Size: 24


In [101]:
def get_tensor_attributes(tensor):
    shape = tensor.shape
    rank = tensor.ndim
    size = tf.size(tensor)
    d_type = tensor.dtype
    
    return f'Shape: {shape}, Rank: {rank}, Size: {size}, Datatype: {d_type}'

In [100]:
print(get_tensor_attributes(p_A))

Shape: (4, 6), Rank: 2, Size: 24, Datatype: <dtype: 'int32'>


In [98]:
print(p_A.dtype)

<dtype: 'int32'>
