# **Introduction to TensorFlow**

## **Creating tensors**

#### **Using tf.constant()**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
print(tf.__version__)

2024-07-02 10:18:58.659323: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


2.4.1


In [2]:
scalar = tf.constant(7)

2024-07-02 10:19:00.365909: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-07-02 10:19:00.370439: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-07-02 10:19:00.602526: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-07-02 10:19:00.602575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2024-07-02 10:19:00.602588: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2024-07-02 10:19:00.632830: I tensorflow/stream_executor/platf

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([42, 42])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[42, 24],
                      [42, 24]])

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
matrix_2 = tf.constant([[42, 24],
                        [42, 24],
                        [12, 21]], dtype = tf.float16)

In [12]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.],
       [12., 21.]], dtype=float16)>

In [13]:
matrix_2.ndim

2

In [14]:
tensor = tf.constant([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

In [15]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [16]:
tensor.ndim

3

#### **Using tf.variable()**

In [17]:
changeable_tensor = tf.Variable([42, 24])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([42, 24], dtype=int32)>

In [18]:
unchangeable_tensor = tf.constant([42, 24])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 24], dtype=int32)>

In [19]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [20]:
# TypeError: 'ResourceVariable' object does not support item assignment
# changeable_tensor[0] = 24

In [21]:
changeable_tensor[0].assign(24)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [22]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([24, 24], dtype=int32)>

In [23]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [24]:
# TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
# unchangeable_tensor[0] = 24

In [25]:
# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'
# unchangeable_tensor[0].assign(24)

#### **Creating random tensors**

In [26]:
random_1 = tf.random.Generator.from_seed(42)

In [27]:
random_1

In [28]:
random_1 = random_1.normal(shape = (3, 2))

In [29]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [30]:
random_2 = tf.random.Generator.from_seed(42)

In [31]:
random_2

In [32]:
random_2 = random_2.normal(shape = (3, 2))

In [33]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [34]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [35]:
tf.random.set_seed(42)
tf.random.shuffle(random_1, seed = 24)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

#### **Create tensors using numpy arrays and pandas dataframes**

In [36]:
tf.ones(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [37]:
tf.zeros(shape = (4, 2), dtype = 'int32')

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [38]:
numpy_A = np.arange(1, 25, dtype = np.int32)

In [39]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [40]:
numpy_A = numpy_A.reshape((4, 6))

In [41]:
n_A = tf.constant(numpy_A)

In [42]:
n_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [43]:
n_B = tf.constant(numpy_A, shape = (2, 3, 4))

In [44]:
n_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [45]:
pandas_A = pd.DataFrame(numpy_A)

In [46]:
pandas_A

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24

In [47]:
p_A = tf.constant(pandas_A)

In [48]:
p_A

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [49]:
p_B = tf.constant(pandas_A, shape = (2, 3, 4))

In [50]:
p_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [51]:
p_B.ndim

3

## **Getting information from tensors**

In [52]:
print(f'Shape: {p_A.shape}, Rank: {p_A.ndim}, Size: {tf.size(p_A)}')

Shape: (4, 6), Rank: 2, Size: 24


In [53]:
import re
def get_tensor_attributes(tensor):
    shape = tensor.shape
    rank = tensor.ndim
    size = tf.size(tensor)
    d_type = f'{tensor.dtype}'.split(':')[1]
    d_type = re.sub(r'[\W]', '', d_type)
    
    return shape, rank, size, d_type

In [54]:
shape, rank, size, d_type = get_tensor_attributes(p_A)
print(f'Shape: {shape}, Rank: {rank}, Size: {size}, Datatype: {d_type}')

Shape: (4, 6), Rank: 2, Size: 24, Datatype: int32


## **Indexing tensors**

In [55]:
rank_4_tensor = tf.constant(np.arange(1, 121), shape = (2, 3, 4, 5))

In [56]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [57]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]])>

In [58]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [59]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int64, numpy=
array([[[[ 1],
         [ 6],
         [11],
         [16]]]])>

In [60]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=int64, numpy=
array([[[[ 1]],

        [[21]],

        [[41]]]])>

In [61]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int64, numpy=
array([[[[ 1]]],


       [[[61]]]])>

In [62]:
rank_2_tensor = tf.reshape(rank_4_tensor, shape = (8, 15))

In [63]:
rank_2_tensor

<tf.Tensor: shape=(8, 15), dtype=int64, numpy=
array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
         59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120]])>

In [64]:
rank_2_tensor[:, :5]

<tf.Tensor: shape=(8, 5), dtype=int64, numpy=
array([[  1,   2,   3,   4,   5],
       [ 16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35],
       [ 46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65],
       [ 76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95],
       [106, 107, 108, 109, 110]])>

In [65]:
rank_2_tensor_1 = tf.constant([[42, 24], [21, 12]])

In [66]:
rank_2_tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [67]:
rank_2_tensor_1[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([24, 12], dtype=int32)>

In [68]:
rank_3_tensor = rank_2_tensor_1[..., tf.newaxis]

In [69]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[42],
        [24]],

       [[21],
        [12]]], dtype=int32)>

In [70]:
tf.expand_dims(rank_2_tensor_1, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[42],
        [24]],

       [[21],
        [12]]], dtype=int32)>

## **Manupilating tensors**

In [71]:
some_tensor = tf.constant([[42, 24], [21, 12]])

In [72]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [73]:
some_tensor = some_tensor + 42

In [74]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[84, 66],
       [63, 54]], dtype=int32)>

In [75]:
some_tensor = some_tensor - 42

In [76]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [77]:
some_tensor = some_tensor * 4

In [78]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[168,  96],
       [ 84,  48]], dtype=int32)>

In [79]:
some_tensor = some_tensor // 4

In [80]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [21, 12]], dtype=int32)>

In [81]:
some_tensor = some_tensor / 2

In [82]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[21. , 12. ],
       [10.5,  6. ]])>

In [83]:
import numpy as np

In [84]:
some_tensor = np.sqrt(some_tensor)

In [85]:
some_tensor

array([[4.58257569, 3.46410162],
       [3.24037035, 2.44948974]])

In [86]:
some_tensor = pow(some_tensor, 2)

In [87]:
some_tensor

array([[21. , 12. ],
       [10.5,  6. ]])

In [88]:
some_tensor = some_tensor * 2 

In [89]:
some_tensor

array([[42., 24.],
       [21., 12.]])

In [90]:
some_tensor = tf.cast(some_tensor, 'int32')

In [91]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 23],
       [21, 11]], dtype=int32)>

In [92]:
tf.math.add(some_tensor, 8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 31],
       [29, 19]], dtype=int32)>

In [93]:
tf.math.subtract(some_tensor, 13)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 10],
       [ 8, -2]], dtype=int32)>

In [94]:
tf.math.multiply(some_tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[168,  92],
       [ 84,  44]], dtype=int32)>

In [95]:
tf.math.divide(some_tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[14.        ,  7.66666667],
       [ 7.        ,  3.66666667]])>

## **Matrix multiplication**

In [96]:
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 23],
       [21, 11]], dtype=int32)>

In [97]:
some_tensor_t = tf.transpose(some_tensor)

In [98]:
some_tensor_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 21],
       [23, 11]], dtype=int32)>

In [99]:
tf.math.multiply(some_tensor, some_tensor_t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1764,  483],
       [ 483,  121]], dtype=int32)>

In [100]:
tf.linalg.matmul(some_tensor, some_tensor_t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2293, 1135],
       [1135,  562]], dtype=int32)>

In [101]:
matrix1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

In [102]:
matrix2 = tf.constant([
    [7, 8],
    [10, 11],
    [13, 14]
])

In [103]:
tf.linalg.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 66,  72],
       [156, 171]], dtype=int32)>

In [104]:
matrix3 = tf.constant(np.random.randint(1, 100, 12).reshape(3, 4))

In [105]:
matrix3

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[21, 65, 71, 94],
       [76, 29, 21, 22],
       [23, 99, 88,  2]])>

In [106]:
matrix4 = tf.constant(np.random.randint(1, 100, 8).reshape(4, 2))

In [107]:
matrix4

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[36, 41],
       [47, 95],
       [ 9,  6],
       [18, 46]])>

In [108]:
tf.tensordot(matrix3, matrix4, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 6142, 11786],
       [ 4684,  7009],
       [ 6309, 10968]])>

In [109]:
tf.matmul(matrix3, matrix4)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 6142, 11786],
       [ 4684,  7009],
       [ 6309, 10968]])>

## **Changing tensors datatype**

In [110]:
matrix3 = tf.cast(matrix3, dtype = tf.int32)

In [111]:
matrix4 = tf.cast(matrix4, dtype = tf.int32)

In [112]:
tf.matmul(matrix3, matrix4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6142, 11786],
       [ 4684,  7009],
       [ 6309, 10968]], dtype=int32)>

## **Aggregating the tensor**

In [113]:
tf.reduce_max(matrix4)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [114]:
tf.reduce_min(matrix4)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [115]:
tf.reduce_mean(matrix4)

<tf.Tensor: shape=(), dtype=int32, numpy=37>

In [116]:
tf.reduce_sum(matrix4)

<tf.Tensor: shape=(), dtype=int32, numpy=298>

In [117]:
sum(sum(matrix4))

<tf.Tensor: shape=(), dtype=int32, numpy=298>

In [118]:
tf.reduce_prod(matrix4)

<tf.Tensor: shape=(), dtype=int32, numpy=-1685461344>

In [119]:
std = tf.math.reduce_std(tf.cast(matrix4, dtype = 'float32'))

In [120]:
var = tf.math.reduce_variance(tf.cast(matrix4, dtype = 'float32'))

In [121]:
std, var

(<tf.Tensor: shape=(), dtype=float32, numpy=26.61649>,
 <tf.Tensor: shape=(), dtype=float32, numpy=708.4375>)

In [122]:
np.std(matrix4)

26.61648925008706

In [123]:
np.var(matrix4)

708.4375

In [124]:
tf.argmin(matrix4, axis = 0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [125]:
tf.argmin(matrix4, axis = 1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 1, 0])>

In [126]:
tf.argmin(matrix3, axis = 0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 1, 2])>

In [127]:
tf.argmin(matrix3, axis = 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 3])>

## **Squeezing tensors**

In [133]:
tf.random.set_seed(42)
matrix5 = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))

In [134]:
matrix5

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [135]:
matrix5_squeezed = tf.squeeze(matrix5)

In [136]:
matrix5_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## **One-hot encoding**

In [147]:
colors = [0, 1, 2, 3]

In [152]:
tf.one_hot(colors, depth = len(colors))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## **Some math funtions**

In [154]:
matrix6 = tf.range(1, 13)

In [156]:
matrix6 = tf.reshape(matrix6, shape = (3, 4))

In [157]:
matrix6

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [158]:
tf.square(matrix6)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]], dtype=int32)>

In [160]:
tf.sqrt(tf.cast(matrix6, dtype = tf.float32))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.6457512, 2.828427 ],
       [3.       , 3.1622777, 3.3166249, 3.4641016]], dtype=float32)>

In [162]:
tf.math.cumsum(matrix6, axis = 1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)>

In [164]:
tf.math.log(tf.cast(matrix6, dtype = tf.float32))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123, 1.3862944],
       [1.609438 , 1.7917595, 1.9459102, 2.0794415],
       [2.1972246, 2.3025851, 2.3978953, 2.4849067]], dtype=float32)>

In [169]:
tf.math.pow(matrix6, 3)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]], dtype=int32)>

## **Tensorflow and numpy compatibility**

In [171]:
matrix7 = tf.constant(np.array([42., 24., 12.]))

In [172]:
matrix7

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([42., 24., 12.])>

In [173]:
type(matrix7)

tensorflow.python.framework.ops.EagerTensor

In [177]:
matrix8 = np.array(matrix7)

In [178]:
type(matrix8)

numpy.ndarray

In [179]:
matrix7.dtype

tf.float64

In [180]:
matrix6.dtype

tf.int32

In [181]:
tf.cast(matrix6, dtype = matrix7.dtype)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])>

## **Using GPU**

In [182]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [183]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [184]:
!nvidia-smi

Tue Jul  2 20:59:06 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        On  |   00000000:01:00.0  On |                  N/A |
|  0%   42C    P8             14W /  170W |   11159MiB /  12288MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## **EXERCISES**

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [187]:
ex_scalar = tf.constant(42)

In [190]:
ex_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [189]:
ex_vector = tf.constant([42, 42])

In [191]:
ex_vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [192]:
ex_matrix = tf.constant([[42, 24], [24, 42]])

In [193]:
ex_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [24, 42]], dtype=int32)>

In [194]:
ex_tensor = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [195]:
ex_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [201]:
ex_scalar.shape, ex_scalar.ndim, tf.shape(ex_scalar)

(TensorShape([]),
 0,
 <tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>)

In [202]:
ex_vector.shape, ex_vector.ndim, tf.shape(ex_vector)

(TensorShape([2]),
 1,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>)

In [203]:
ex_matrix.shape, ex_matrix.ndim, tf.shape(ex_matrix)

(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>)

In [204]:
ex_tensor.shape, ex_tensor.ndim, tf.shape(ex_tensor)

(TensorShape([2, 2, 3]),
 3,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [241]:
tf.random.set_seed(42)
ex_tensor1 = tf.random.uniform(shape = (5, 300))

In [242]:
ex_tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [243]:
tf.random.set_seed(24)
ex_tensor2 = tf.random.uniform(shape = (5, 300))

In [244]:
ex_tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.10927987, 0.26020873, 0.7633631 , ..., 0.5732243 , 0.29622567,
        0.5584904 ],
       [0.40879428, 0.01851249, 0.06484127, ..., 0.74509406, 0.7762246 ,
        0.49130988],
       [0.37870276, 0.17573595, 0.01397479, ..., 0.41859305, 0.49424505,
        0.3922186 ],
       [0.545331  , 0.99168897, 0.69376755, ..., 0.35077906, 0.5223229 ,
        0.68388844],
       [0.37977195, 0.8442526 , 0.2177831 , ..., 0.42251897, 0.59477377,
        0.38484502]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [245]:
tf.math.multiply(ex_tensor1, ex_tensor2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.07262326, 0.11475381, 0.2693775 , ..., 0.18005243, 0.22494   ,
        0.02065885],
       [0.21748838, 0.00539268, 0.00685487, ..., 0.40274042, 0.24393423,
        0.10811859],
       [0.03182697, 0.00635216, 0.01365786, ..., 0.09006718, 0.48367307,
        0.00285044],
       [0.40337834, 0.6597877 , 0.05465695, ..., 0.24967515, 0.03663349,
        0.64347917],
       [0.06023693, 0.10151321, 0.05927671, ..., 0.37286788, 0.08520063,
        0.1698518 ]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [247]:
tf.linalg.matmul(ex_tensor1, ex_tensor2, transpose_b = True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.24629 , 73.54976 , 75.048546, 75.80545 , 78.960106],
       [72.33918 , 71.40964 , 69.97695 , 72.64048 , 72.41999 ],
       [77.53124 , 72.41772 , 72.69784 , 75.74254 , 73.69695 ],
       [71.73841 , 68.16662 , 70.50826 , 74.89098 , 73.03289 ],
       [76.57754 , 75.48809 , 75.52525 , 78.87166 , 75.993614]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [248]:
ex_tensor3 = tf.random.uniform(shape = [224, 224, 3])

In [249]:
ex_tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8875979 , 0.0716151 , 0.38931954],
        [0.52773523, 0.45418775, 0.4545952 ],
        [0.40503561, 0.28862238, 0.20030463],
        ...,
        [0.621035  , 0.42020702, 0.04535997],
        [0.36326027, 0.19628036, 0.86698043],
        [0.16912591, 0.830595  , 0.93398035]],

       [[0.10933232, 0.09066951, 0.95751274],
        [0.88375163, 0.6928458 , 0.7869148 ],
        [0.19057035, 0.19762087, 0.41778326],
        ...,
        [0.996876  , 0.05178726, 0.44400537],
        [0.583006  , 0.6352681 , 0.8380282 ],
        [0.19035923, 0.9259907 , 0.90589535]],

       [[0.9468392 , 0.7157507 , 0.19773316],
        [0.09060764, 0.81029534, 0.19365823],
        [0.736907  , 0.14684665, 0.53045774],
        ...,
        [0.8397001 , 0.7393296 , 0.01585066],
        [0.49944746, 0.66136146, 0.3419224 ],
        [0.16901314, 0.26022243, 0.7991755 ]],

       ...,

       [[0.04374444, 0.08199811, 0.93804646],
        [0.19

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [276]:
tf.reduce_min(ex_tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=3.33786e-06>

In [254]:
tf.math.argmin(ex_tensor3)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[176, 188, 220],
       [ 80, 119,  56],
       [ 99, 218, 143],
       [ 63, 157, 195],
       [185, 160, 214],
       [ 37, 164,  88],
       [142, 207,  19],
       [163,  87,  25],
       [ 17, 222, 193],
       [118,  67, 223],
       [203,  60, 169],
       [  1, 223,  10],
       [ 85,  38,  43],
       [ 32,   0,  60],
       [ 92, 129,  45],
       [217,   9, 111],
       [113,  34, 208],
       [ 17,  80, 188],
       [164, 173, 131],
       [  2,  86, 212],
       [ 91,  92,  78],
       [  2,  35, 165],
       [ 35, 117, 133],
       [ 84,  58,   9],
       [ 39, 195, 176],
       [  6, 171, 118],
       [ 92, 211, 141],
       [ 24, 120,  83],
       [135,  56,  19],
       [ 92, 105, 130],
       [ 54, 134, 192],
       [209, 195,  36],
       [200,  37, 206],
       [ 22,  80, 223],
       [ 40, 151, 140],
       [ 33, 108,  64],
       [ 70,  58, 191],
       [ 31, 153, 137],
       [145, 192, 180],
       [ 24, 159

In [277]:
tf.reduce_max(ex_tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999654>

In [258]:
tf.math.argmax(ex_tensor3)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[184,  72, 150],
       [  6,  74,   4],
       [ 47, 179,  11],
       [ 85, 116,  58],
       [198,  82, 128],
       [192, 140, 157],
       [ 11,  44,  93],
       [ 43, 207,  56],
       [164,  66, 126],
       [ 53, 175, 196],
       [133, 152, 201],
       [140,  36,  27],
       [171,   9, 222],
       [ 43, 165, 124],
       [ 76, 150, 171],
       [187, 217,  97],
       [ 82,   2, 121],
       [211, 193, 128],
       [200, 163,  21],
       [206,  35,   6],
       [220, 168,  85],
       [107, 147,   3],
       [161,  29,  52],
       [223,  33, 207],
       [138,  12, 113],
       [139,  31, 148],
       [156, 136,  18],
       [ 61, 175, 106],
       [ 96, 126,  71],
       [ 19,  42,  36],
       [174, 158, 140],
       [178,   0,  57],
       [ 44,  27, 154],
       [163, 211, 154],
       [133, 201, 128],
       [136,  25, 124],
       [196, 151,  96],
       [102, 188,  71],
       [ 38,  22, 129],
       [184,  56

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [259]:
ex_tensor4 = tf.random.uniform(shape = [1, 224, 224, 3])

In [260]:
ex_tensor4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.02866328, 0.2507794 , 0.002689  ],
         [0.19168532, 0.42840004, 0.2519921 ],
         [0.4648975 , 0.59043145, 0.05508101],
         ...,
         [0.888669  , 0.83945537, 0.8281572 ],
         [0.19150293, 0.893674  , 0.9514446 ],
         [0.3176663 , 0.24304628, 0.04342258]],

        [[0.3677417 , 0.51699364, 0.65426743],
         [0.06444144, 0.7819259 , 0.52699375],
         [0.21994984, 0.21415746, 0.6586517 ],
         ...,
         [0.46270788, 0.23782086, 0.58373606],
         [0.7695863 , 0.93288875, 0.06555784],
         [0.5962955 , 0.5740706 , 0.9934752 ]],

        [[0.96053195, 0.30053437, 0.8458246 ],
         [0.38486123, 0.6588348 , 0.08408225],
         [0.19266343, 0.70268023, 0.21531463],
         ...,
         [0.1396352 , 0.84044325, 0.31729698],
         [0.9671625 , 0.60597694, 0.9017806 ],
         [0.6013273 , 0.60185575, 0.5133368 ]],

        ...,

        [[0.7982224 , 0.6527921 , 

In [261]:
ex_tensor4_sq = tf.squeeze(ex_tensor4)

In [263]:
ex_tensor4_sq

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.02866328, 0.2507794 , 0.002689  ],
        [0.19168532, 0.42840004, 0.2519921 ],
        [0.4648975 , 0.59043145, 0.05508101],
        ...,
        [0.888669  , 0.83945537, 0.8281572 ],
        [0.19150293, 0.893674  , 0.9514446 ],
        [0.3176663 , 0.24304628, 0.04342258]],

       [[0.3677417 , 0.51699364, 0.65426743],
        [0.06444144, 0.7819259 , 0.52699375],
        [0.21994984, 0.21415746, 0.6586517 ],
        ...,
        [0.46270788, 0.23782086, 0.58373606],
        [0.7695863 , 0.93288875, 0.06555784],
        [0.5962955 , 0.5740706 , 0.9934752 ]],

       [[0.96053195, 0.30053437, 0.8458246 ],
        [0.38486123, 0.6588348 , 0.08408225],
        [0.19266343, 0.70268023, 0.21531463],
        ...,
        [0.1396352 , 0.84044325, 0.31729698],
        [0.9671625 , 0.60597694, 0.9017806 ],
        [0.6013273 , 0.60185575, 0.5133368 ]],

       ...,

       [[0.7982224 , 0.6527921 , 0.38077664],
        [0.87

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [273]:
ex_tensor5 = tf.constant([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [274]:
tf.argmax(ex_tensor5)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

10. One-hot encode the tensor you created in 9.

In [275]:
tf.one_hot(ex_tensor5, depth = len(ex_tensor5))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>